-- ==========================================
-- Maven Toys Sales Analysis
-- SQL Server
-- ==========================================

use toystore;

----------------------------------------------
--- Revenue Analysis
----------------------------------------------

/*Which 10 products generated the highest revenue?*/

SELECT TOP 10
       p.product_name,
       SUM(s.units * p.product_price) AS revenue
FROM products p
JOIN sales s
    ON p.product_id = s.product_id
GROUP BY p.product_name
ORDER BY revenue DESC;

/*Show the revenue generated by every city, from highest to lowest.*/

select s.store_city,sum(ss.units*p.product_price) as revenue from stores s
join sales ss
on s.Store_ID= ss.store_id
join products p
on p.product_id=ss.product_id
group by s.Store_City
order by revenue desc;

/*Show each product category with:
Total Revenue
Total Units Sold*/

SELECT p.Product_Category, sum(s.units) as unitssold,sum(s.units*p.product_price) as Revenue
from products p
join sales s
ON s.Product_ID=p.Product_ID
GROUP BY p.Product_Category
ORDER BY Revenue desc;

/*Show the Top 3 products by revenue within each product category.*/
SELECT
    t.product_category,
    t.product_name,
    t.revenue
FROM
(
    SELECT
        p.product_category,
        p.product_name,
        SUM(s.units * p.product_price) AS revenue,
        DENSE_RANK() OVER
        (
            PARTITION BY p.product_category
            ORDER BY SUM(s.units * p.product_price) DESC
        ) AS drnk
    FROM products p
    JOIN sales s
        ON p.product_id = s.product_id
    GROUP BY
        p.product_category,
        p.product_name
) AS t
WHERE t.drnk <= 3
ORDER BY
    t.product_category,
    t.revenue DESC;

/*Which are the Top 10 stores based on total revenue?*/

select top 10
ss.store_name,ss.store_city,sum(s.units*p.product_price) as revenue
from stores ss
join sales s
on s.store_id=ss.store_ID
join products p
on p.Product_ID=s.Product_ID
group by ss.Store_City,ss.Store_Name
order by revenue desc;

----------------------------------------------------
--- Profit Analysis
----------------------------------------------------


/*Which product generated the highest profit?*/

select top 1
p.product_name,(sum(s.units*(p.product_price-p.product_cost))) as profit
from products p
join sales s
on s.Product_ID=p.Product_ID
group by p.Product_Name
order by profit desc;

/*Which product category generated the highest profit?*/

select top 1
p.Product_Category,(sum(s.units*(p.product_price-p.product_cost))) as profit
from products p
join sales s
on s.Product_ID=p.Product_ID
group by p.Product_Category
order by profit desc;

/*Show the Top 5 Most Profitable Products.*/

select top 5
p.product_name,(sum(s.units*(p.product_price-p.product_cost))) as profit,sum(s.units*p.product_cost)as cost,
SUM(s.units * p.product_price) AS revenue from products p
join sales s
on s.Product_ID=p.Product_ID
group by p.Product_Name
order by profit desc;

/*Show the Profit Margin (%) for every product.*/

with productprofit as
( select p.product_name,(sum(s.units*(p.product_price-p.product_cost))) as profit,sum(s.units*p.product_cost)as cost,
SUM(s.units * p.product_price) AS revenue from products p
join sales s
on s.Product_ID=p.Product_ID
group by p.Product_Name
)
select product_name,profit,revenue,
(profit/nullif (revenue,0))*100 as profit_margin
from productprofit
order by profit desc;

/*For every product category, show the Top 3 products by profit.*/

with storerev as
( 
select p.product_category,p.product_name,sum(s.units*(p.product_price-p.product_cost)) as profit,
dense_rank() over(partition by p.product_category
order by sum(s.units*(p.product_price-p.product_cost))desc) as drnk
from products p
join sales s
on p.product_id=s.Product_ID
group by p.Product_Category,p.Product_Name)
select product_category,product_name,profit from storerev 
where drnk<=3;

---------------------------------------------------------
--- Store Analysis
---------------------------------------------------------

/*Which stores are underperforming?*/

with underperform as
( 
select s.store_name,s.store_city,sum(ss.units*product_price) as revenue
from products p
join sales ss 
on ss.product_id=p.Product_ID
join stores s
on s.store_id=ss.Store_ID
group by s.store_name,s.store_city
)
select store_name,store_city,revenue,
case 
 when revenue>=500000 then 'Excellent'
when revenue between 300000 and 499999 then 'good'
else 'needs improvement'
 end as performance
 from underperform
order by revenue desc;

/*Find the highest revenue store in each city.*/

with highrevenue as
(
select s.store_city,s.store_name,sum(ss.units*p.product_price) as revenue,
dense_rank() over( partition by store_city ORDER BY sum(ss.units*p.product_price)desc
)as drnk
from products p
join sales ss 
on ss.product_id=p.Product_ID
join stores s
on s.store_id=ss.Store_ID
group by s.store_name,s.store_city
) select store_city,store_name,revenue from highrevenue
where drnk=1;

------------------------------------------------------------------
---Product Analysis
------------------------------------------------------------------

/*Find the highest revenue product in each product category*/

with storerev as
( 
select p.product_category,p.product_name,sum(s.units*p.product_price) as revenue,
dense_rank() over(partition by p.product_category
order by sum(s.units*p.product_price)desc) as drnk
from products p
join sales s
on p.product_id=s.Product_ID
group by p.Product_Category,p.Product_Name)
select product_category,product_name,revenue from storerev 
where drnk=1;

-----------------------------------------------------------------
---Time Analysis
-----------------------------------------------------------------

/*How much revenue was generated each month?*/

SELECT
    MONTH(s.date) AS month_number,
    DATENAME(MONTH, s.date) AS month_name,
    SUM(s.units * p.product_price) AS revenue
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    MONTH(s.date),
    DATENAME(MONTH, s.date)
ORDER BY
    month_number;


/*Which month generated the highest revenue?*/

SELECT TOP 1
    MONTH(s.date) AS monthnum,
    DATENAME(MONTH, s.date) AS monthname,
    SUM(s.units * p.product_price) AS revenue
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY
    MONTH(s.date),
    DATENAME(MONTH, s.date)
ORDER BY
    revenue DESC;

/*Which quarter generated the highest revenue?*/

select top 1 DATEPART(quarter,s.date)as quarterrev,
sum(s.units*p.product_price) as revenue
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY DATEPART(quarter,s.date)
order by revenue desc;

/*Which year generated the highest revenue*/

select top 1 year(s.date)as yearrev,
sum(s.units*p.product_price) as revenue
FROM sales s
JOIN products p
    ON s.product_id = p.product_id
GROUP BY year(s.date)
order by revenue desc;

-----------------------------------------------------------------

/*Show only the product categories whose total revenue is greater than ₹500,000.*/

select p.product_category,sum(s.units*p.product_price) as revenue
from products p
join sales s
 ON s.product_id = p.product_id
 group by p.Product_Category
 having sum(s.units*p.product_price) >500000
 order by revenue desc;

 /*Show the cumulative (running) revenue over time.*/

with dailyrev as(
 select s.date,
 sum(s.units*p.product_price) as revenue
 from products p
 join sales s
 on s.Product_ID=p.Product_ID
 group by s.date)
 select date,revenue,
 sum(revenue) over
 (order by date
 )as runningtotal
 from dailyrev;


/*How much did revenue increase or decrease compared to the previous day?*/

 with dailyrev as(
 select s.date,
 sum(s.units*p.product_price) as revenue
 from products p
 join sales s
 on s.Product_ID=p.Product_ID
 group by s.date),

 revcompare as(
  select date,revenue,
 LAG(revenue) over(order by date) as prevdayrev
 from dailyrev)
 SELECT
    date,
    revenue,
    prevdayrev,
    revenue - prevdayrev AS difference
FROM revcompare;

